easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'

  entities:
    Skill:
      class: 'App\Entity\Skill'
      label: 'Skills'
      list:
        title: 'List of Skills'
        fields:
          - { property: 'id', label: 'ID' }
          - { property: 'slug', label: 'Slug' }
          - { property: 'name', label: 'Name' }
      form:
        title: 'Edit Skill'
        fields:
          - { property: 'name', label: 'Name' }
          - { property: 'description', label: 'Description' }
          - { property: 'slug', label: 'Slug' }

    Article:
      class: 'App\Entity\Article'
      label: 'Articles'
      form:
        fields:
          - { property: 'title', label: 'Title' }
          - { property: 'text', label: 'Text'}